services:
  api:
    build: .
    restart: always
    ports:
     - 8000:80
  my-app:
    build: react_js/.
    ports:
      - 3000:80
    restart: always
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: example
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  get:
    build: 
      context: .
      dockerfile: psycop.Dockerfile
    restart: always
    depends_on:
     - db
  
